[build]
  functions = "src/functions"
  publish = "public"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=(self)"
    Access-Control-Allow-Origin = "*"
